version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cantik-backend
    restart: unless-stopped
    network_mode: "host" 
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - ./backend/.env