version: '3.8'

services:
  # --- BACKEND API ---
  backend:
    build: ./backend
    container_name: cantik-backend
    restart: unless-stopped
    network_mode: "host" 
    volumes:
      # Jalur VPS diarahkan ke folder backend/uploads agar sesuai struktur baru Anda
      - /www/wwwroot/skin-analyzer.cantik.ai/backend/uploads:/app/uploads
    env_file:
      - ./backend/.env

  # --- FRONTEND PWA ---
  frontend-pwa:
    build: 
      context: ./platforms/pwa
      dockerfile: Dockerfile
    container_name: cantik-fe-pwa
    # Tetap menggunakan port 3001 agar bisa di-proxy oleh aaPanel
    ports:
      - "3001:80"
    restart: always